### ISSUE TITLE
[WEBSITE]: Icons does not work on auth pages

### ISSUE THREAD

**Issue by mauro-balades** [wonoly/roadmap#11]
## Description

Add font awesome link for icons to work.

## Roadmap

* [ ] Add library link for the login page
* [ ] Add library link for the register page

**Comment by WillTheDeveloper** [comment]
Can you elaborate? Or is it simply, font awesome link needs to be added so the lil icons work? @mauro-balades

**Comment by mauro-balades** [comment]
font awesome link needs to be added so the lil icons work

**Comment by WillTheDeveloper** [comment]
Alright, can it wait till I get to the UK? @mauro-balades It's relatively easy. Maybe I could do it on my phone.

**Comment by WillTheDeveloper** [comment]
Wait, this is a Laravel project right? I think there is documentation specifically for it so you can install it and not need to reference it via a url link if that makes sense. On one of my old projects, I had just done this.

**Comment by mauro-balades** [comment]
> Alright, can it wait till I get to the UK? @mauro-balades It's relatively easy. Maybe I could do it on my phone.

Dont worry @WillTheDeveloper . Do it when you come back. It is not the biggest priority
