### ISSUE TITLE
[SEARCH ENGINE]: Cookies consent message stylings

### ISSUE THREAD

**Issue by mauro-balades** [wonoly/roadmap#2]
## Description

Add some stylings to the default cookies messages.

* Library: https://github.com/justijndepover/laravel-cookie-consent
* Expanded from: https://github.com/wonoly/roadmap/issues/1

## Roadmap

* [ ] Change the `accept` styling button to a black background with white text
* [ ] Add a border to the message.

**Comment by WillTheDeveloper** [comment]
Cookies* is the correct word.
