### ISSUE TITLE
[WEBSITE]: Add support for profile images

### ISSUE THREAD

**Issue by mauro-balades** [wonoly/roadmap#29]
# Sumary

Add support for profile images

# Roadmap

* Backend for profile images
* Add images
* Default profile image
* Change image
* Delete image

**Comment by mauro-balades** [comment]
> https://jetstream.laravel.com/2.x/features/profile-management.html#profile-photos

thanks, I will check it out.

**Comment by WillTheDeveloper** [comment]
No problem! If you have any issues just let me take over

**Comment by mauro-balades** [comment]
Alright, I already activated them. https://github.com/WillTheDeveloper/Wonoly-V2/commit/6f3dea069adfaf8bb2e6a985baeaa8582179968a
