### ISSUE TITLE
[REQUEST]: Elevated permission to help with roadmap

### ISSUE THREAD

**Issue by WillTheDeveloper** [wonoly/roadmap#3]
# Request

Can I have elevated permissions on this repository so I can help build the roadmap? There are loads of things that need to be added and I can do it. @mauro-balades

**Comment by mauro-balades** [comment]
> # Request
> 
> Can I have elevated permissions on this repository so I can help build the roadmap? There are loads of things that need to be added and I can do it. @mauro-balades 

I m on it.

**Comment by WillTheDeveloper** [comment]
Thank you.
